/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author tancincoja_sd2022
 */
public class pharmacistView extends javax.swing.JFrame {

    /**
     * Creates new form adminView
     */
    String uname = "Admin";

    public pharmacistView() {
        initComponents();
        this.setTitle("Menu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pharmaPanel = new javax.swing.JPanel();
        Menu = new javax.swing.JLabel();
        addMedButton = new javax.swing.JButton();
        removeMedButton = new javax.swing.JButton();
        displayMedButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pharmaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        Menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu.setText("Menu");
        pharmaPanel.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 11, -1, -1));

        addMedButton.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        addMedButton.setText("Add Medicine");
        addMedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMedButtonMouseClicked(evt);
            }
        });
        addMedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedButtonActionPerformed(evt);
            }
        });
        pharmaPanel.add(addMedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 220, 100));

        removeMedButton.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        removeMedButton.setText("Remove Medicine");
        removeMedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeMedButtonMouseClicked(evt);
            }
        });
        pharmaPanel.add(removeMedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 220, 100));

        displayMedButton.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        displayMedButton.setText("Display Medicine");
        displayMedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayMedButtonMouseClicked(evt);
            }
        });
        pharmaPanel.add(displayMedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 220, 100));

        logOutButton.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        pharmaPanel.add(logOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 220, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pharmaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pharmaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        this.setVisible(false);
        Home home = null;
        try {
            home = new Home();
            home.setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(pharmacistView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_logOutButtonActionPerformed

    private void addMedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMedButtonMouseClicked
        this.dispose();
        new addMedicineView().setVisible(true);
    }//GEN-LAST:event_addMedButtonMouseClicked

    private void removeMedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMedButtonMouseClicked
        this.dispose();
        new removeMedicineView().setVisible(true);
    }//GEN-LAST:event_removeMedButtonMouseClicked

    private void displayMedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayMedButtonMouseClicked
//        this.dispose();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        new viewMedTable(uname).setVisible(true);
    }//GEN-LAST:event_displayMedButtonMouseClicked

    private void addMedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMedButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pharmacistView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pharmacistView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pharmacistView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pharmacistView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new pharmacistView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Menu;
    private javax.swing.JButton addMedButton;
    private javax.swing.JButton displayMedButton;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel pharmaPanel;
    private javax.swing.JButton removeMedButton;
    // End of variables declaration//GEN-END:variables
}
