/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controller.Controller;

/**
 *
 * @author tancincoja_sd2022
 */
public class removeMedicineView extends javax.swing.JFrame {

    /**
     * Creates new form removeMedicineView
     */
    public removeMedicineView() {
        initComponents();
        this.setTitle("Remove Medicine");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeMedicinePanel = new javax.swing.JPanel();
        removeMedicineLabel = new javax.swing.JLabel();
        upSeparator = new javax.swing.JSeparator();
        medTableView = new javax.swing.JScrollPane();
        medTable = new javax.swing.JTable();
        brandNameLabel = new javax.swing.JLabel();
        downSeparator = new javax.swing.JSeparator();
        inputName = new javax.swing.JTextField();
        removeButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        viewMedButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        removeMedicineLabel.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        removeMedicineLabel.setText("Remove Medicine");

        medTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Generic Name", "Brand Name", "Medicine Type", "Price", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        medTableView.setViewportView(medTable);

        brandNameLabel.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        brandNameLabel.setText("Enter Brand Name to remove:");

        inputName.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        inputName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });

        removeButton.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        removeButton.setText("Remove");
        removeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeButtonMouseClicked(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        viewMedButton.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        viewMedButton.setText("View");
        viewMedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMedButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout removeMedicinePanelLayout = new javax.swing.GroupLayout(removeMedicinePanel);
        removeMedicinePanel.setLayout(removeMedicinePanelLayout);
        removeMedicinePanelLayout.setHorizontalGroup(
            removeMedicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removeMedicinePanelLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(removeMedicineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(228, 228, 228))
            .addComponent(upSeparator)
            .addComponent(downSeparator)
            .addGroup(removeMedicinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(medTableView)
                .addGap(13, 13, 13))
            .addGroup(removeMedicinePanelLayout.createSequentialGroup()
                .addGroup(removeMedicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeMedicinePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(brandNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(removeMedicinePanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(viewMedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(59, 59, 59)))
                .addGroup(removeMedicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeMedicinePanelLayout.createSequentialGroup()
                        .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(75, 75, 75)
                        .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(64, 64, 64))
                    .addGroup(removeMedicinePanelLayout.createSequentialGroup()
                        .addComponent(inputName)
                        .addGap(21, 21, 21))))
        );
        removeMedicinePanelLayout.setVerticalGroup(
            removeMedicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removeMedicinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(removeMedicineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medTableView, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(downSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(removeMedicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(inputName))
                .addGap(58, 58, 58)
                .addGroup(removeMedicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewMedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(removeMedicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removeMedicinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(removeMedicinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        this.dispose();
        new pharmacistView().setVisible(true);
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void viewMedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMedButtonMouseClicked
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jframe", "root", "");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM `medicine`");
            DefaultTableModel tm = (DefaultTableModel) medTable.getModel();
            tm.setRowCount(0);
            
            while (rs.next()) {
                Object table[] = {rs.getInt("id"), rs.getString("genericname"), rs.getString("brandname"), rs.getString("medicinetype"), rs.getDouble("price"), rs.getInt("stock")};
                tm.addRow(table);
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Error connecting to database!");
        }
    }//GEN-LAST:event_viewMedButtonMouseClicked

    private void removeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeButtonMouseClicked
        String bname = inputName.getText(); // inputted text from the view
        
        Controller medControl = new Controller();
        if (medControl.removeMedicine(bname) == true) {
            JOptionPane.showMessageDialog(rootPane, "Successfully removed!"); // tells us that it is successful  
            this.dispose();
            new pharmacistView().setVisible(true);  // page will go back to the pharmacist menu view
            }        
    }//GEN-LAST:event_removeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(removeMedicineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(removeMedicineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(removeMedicineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(removeMedicineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new removeMedicineView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brandNameLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JSeparator downSeparator;
    private javax.swing.JTextField inputName;
    private javax.swing.JTable medTable;
    private javax.swing.JScrollPane medTableView;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel removeMedicineLabel;
    private javax.swing.JPanel removeMedicinePanel;
    private javax.swing.JSeparator upSeparator;
    private javax.swing.JButton viewMedButton;
    // End of variables declaration//GEN-END:variables
}
