/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ZJPanelPractice;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author tancincoja_sd2022
 */
public class PracticeJPanel extends JPanel {

    private JButton b1;
    private JButton b2;
    JFrame f = new JFrame("Home"); 

    public PracticeJPanel() {
        b1 = new JButton();
        b2 = new JButton();
        String login = "Log in";
        String register = "Register";
       
        
        this.setLayout(null);
        f.setLayout(null);       
        this.setBackground(Color.gray);
        this.setVisible(true);
        this.setBorder(BorderFactory.createLineBorder(Color.PINK));
        this.setSize(new Dimension(1920, 1080));
        
        JLabel title = new JLabel("Already have an account?");
        title.setFont(new Font("Serif", Font.BOLD, 60));
        title.setBounds(650, 100, 700, 100);
        this.add(title);
        
        b1.setText(login);
        b1.setFont(new Font("Serif", Font.BOLD, 40));
        b1.setBounds(750, 200, 400, 100);
        this.add(b1);
 
        JLabel title1 = new JLabel("Don't have an account yet?");
        title1.setFont(new Font("Serif", Font.BOLD, 60));
        title1.setBounds(630, 400, 700, 100);
        this.add(title1);
        
        
        b2.setText(register);
        b2.setFont(new Font("Serif", Font.BOLD, 40));
        b2.setBounds(750, 500, 400, 100);
        this.add(b2);
        
        f.add(this); 
        f.setSize(new Dimension(1920, 1080));
        f.show();

        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
